config/routes.rb
Rails.application.routes.draw do
 
 
 devise_for :customers, skip:[:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_for :admin, skip:[:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}



scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/items/search' => 'items#search'
  resources :items, only:[:index, :show]
  resources :genres, only: [:show]
  get '/customers/my_page' => 'customers#show'
  get '/cuntomers/unsubscribe' => 'customers#unsubscribe'
  patch '/customers/withdraw' => 'customers#withdraw'
  resources :customers, only:[:edit, :update]
  resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only:[:new, :create, :index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only:[:index, :update, :destroy, :create]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only:[:new, :create, :index, :show]
end


 namespace :admin do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :genres, only:[:index, :create, :edit, :update, :destroy] 
  resources :items, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  resources :customers, only:[:index, :edit, :update, :show]
  resources :orders, only:[:index, :show, :update]
  resources :order_details, only:[:update]
  end

 
 
  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  validates :postal_code, presence: true, numericality: :only_integer
  validates :address, presence: true
  validates :name, presence: true
  
  def view_address
    postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   
   belongs_to :item
   belongs_to :customer
   
   validates :amount, presence: true
   
   def subtotal
    item.with_tax_price * amount
   end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true, length: { minimum: 6 }
  validates :postal_code, presence: true, numericality: { only_integer: true }
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: { only_integer: true }
  
  def full_name
    first_name + " " + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true , numericality: :only_integer
  
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def get_image(size)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize: size).processed
  end
end

# def get_profile_image(size)
#   unless profile_image.attached?
#     file_path = Rails.root.join('app/assets/images/no_image.jpg')
#     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
#   end
#     profile_image.variant(resize: size).processed
# end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: { 
    payment_waiting: 0, 
    payment_confirmation: 1, 
    in_production: 2, 
    preparing_delivery: 3, 
    delivered: 4 
  }
  
  validates :payment_method, presence: true
  
 
  
  def count_amount
    total = 0
    order_details.each do |order_detail|
      total += order_detail.amount
    end
    return total
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
  
  enum production_status: { 
    production_not_possible: 0, 
    production_pending: 1, 
    in_production: 2, 
    production_complete: 3 
  }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "新しくジャンルを登録しました"
    else
      @genres = Genre.all
      render :index
    end
  end
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンル名を更新しました"
    else
      render :edit
    end
  end
  
  def destroy
    genre = Genre.find(params[:id])  
    genre.destroy  
    redirect_to   admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    range = Date.today.beginning_of_day..Date.today.end_of_day #　本日の0時〜23時59分までのデータを指定
    @orders = Order.where(created_at: range)  # 本日の注文データのみ取ってくる
  end
  
  def about
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @items = Item.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id), notice: "商品を新規登録しました"
    else
      @genres = Genre.all
      render :new
    end
  end
  
  def new
    @item = Item.new
    @genres = Genre.all
  end
 
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
    # @genre = @item.genre
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id), notice: "商品情報を更新しました"
    else
      @genres = Genre.all
      render :edit
    end
  end
  
  def destroy
    item = Item.find(params[:id])  
    item.destroy
    redirect_to admin_items_path
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :genre_id, :name, :introduction, :price, :is_active)  
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
  
  
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_nav.html.erb
<header>
  
  <% if flash[:notice] %>
  
   <div class="alert alert-success" role="alert">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
     <p class="notice text-center alert-dismissible" style="color:green;"><%= flash[:notice] %></p>
   </div>
   
  <% end %>
  
    
     <nav class="navbar navbar-expand-md navbar-light border-bottom">
        <div class="container">
          <button class="btn btn-outline-secondary" type="button"><%= link_to "Logo", admin_root_path, class: 'nav-link text-dark'  %></button>
          
            <% if admin_signed_in? %>
            
            <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
              <ul class="navbar-nav ml-auto">
                
                <li class="mr-3">
                  <button class="btn btn-outline-secondary" type="button"><%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark' %></button>
                </li>
                
                
                <li class="mr-3">
                  <button class="btn btn-outline-secondary" type="button"><%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %></button>
                </li>
                
                <li class="mr-3">
                  <button class="btn btn-outline-secondary" type="button"><%= link_to '注文履歴一覧', admin_orders_path, class: 'nav-link text-dark' %></button>
                  
                </li>
                
                <li class="mr-3">
                   <button class="btn btn-outline-secondary" type="button"><%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-dark' %></button>
                </li>
                
                <li class="mr-3">
                  <button class="btn btn-outline-secondary" type="button"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></button>
                </li>
                
              </ul>
            </div>
        </div>
           <% else %>
           <div class="navbar navbar-expand-lg navbar-light">
             <div class="container">
               <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
                 <ul class="navbar-nav ml-auto">
                   
                    <li class="mr-3">
                      <button class="btn btn-outline-secondary" type="button"><%= link_to 'About', admin_about_path, class: 'nav-link text-dark'  %></button>
                    </li>
                    
                    <li class="mr-3">
                      <button class="btn btn-outline-secondary" type="button"><%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark'  %></button>
                    </li>
                    
                    <li class="mr-3">
                      <button class="btn btn-outline-secondary" type="button"><%= link_to 'ログイン', admin_session_path, class: 'nav-link text-dark'  %></button>
                    </li>
                    
                    <li class="mr-3">
                      <button class="btn btn-outline-secondary" type="button"><%= link_to '顧客ログイン画面へ', new_customer_session_path, class: 'nav-link text-dark'  %></button>
                    </li>
                    
                  </ul>
                </div>
              </div>
            </div>  
            <% end %>
      </nav>
    </header>
    

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash.htrml.erb
  <% if flash[:notice] %>
  
   <div class="alert alert-success" role="alert">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     <p class="notice text-center alert-dismissible" style="color:green;"><%= flash[:notice] %></p>
   </div>
   
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= flash[:alert]%>
    <%= yield %>
  </body>
</html>