config/routes.rb
Rails.application.routes.draw do
 
 
 devise_for :customers, skip:[:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_for :admin, skip:[:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}



scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/items/search' => 'items#search'
  resources :items, only:[:index, :show]
  resources :genres, only: [:show]
  get '/customers/my_page' => 'customers#show'
  get '/cuntomers/unsubscribe' => 'customers#unsubscribe'
  patch '/customers/withdraw' => 'customers#withdraw'
  resources :customers, only:[:edit, :update]
  resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only:[:new, :create, :index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only:[:index, :update, :destroy, :create]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only:[:new, :create, :index, :show]
end


 namespace :admin do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :genres, only:[:index, :create, :edit, :update, :destroy] 
  resources :items, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  resources :customers, only:[:index, :edit, :update, :show]
  resources :orders, only:[:index, :show, :update]
  resources :order_details, only:[:update]
  end

 
 
  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true, length: { minimum: 6 }
  validates :postal_code, presence: true, numericality: { only_integer: true }
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: { only_integer: true }
  
  def full_name
    first_name + " " + last_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
    @customer = current_customer
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: "会員情報を更新しました"
    else
      render :edit
    end
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
    
    private 

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= render 'admin/nav' %>
  <main>
    <div class="container">
      <div class="text-center">
        <div class="row">
          <div class="col-5 mt-5 bg-light">
            <h2><%= @customer.full_name %> 様の会員情報編集</h2>
          </div>       
        </div>
      </div>
      
      <% if @customer.errors.any? %>
        <h5 class="text-danger">
          ※<%= @customer.errors.count %>件のエラーが発生しました
        </h5>
        <ul class="text-danger list-unstyled">
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
        
        <table class="table table-borderless my-4">
          <tbody>
          <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |customer| %>
    
            <tr>
              <th scope="row">氏名</th> 
              <td>
                <%= customer.text_field :first_name %>
                <%= customer.text_field :last_name %>
              </td>
            </tr>
            
            <tr>
              <th scope="row">フリガナ</th>
              <td>
                <%= customer.text_field :first_name_kana %>
                <%= customer.text_field :last_name_kana %>
              </td>
            </tr>
            
            <tr>
               <th scope="row">郵便番号</th>
              <td><%= customer.text_field :postal_code, maxlength: "7" %></td>
            </tr>
            
            <tr>
               <th scope="row">住所</th>
              <td><%= customer.text_field :address, size: '50' %></td>
            </tr>
            
            <tr>
              <th scope="row">電話番号</th>
              <td><%= customer.text_field :telephone_number %></td>
            </tr>
            
            <tr>
              <th scope="row">メールアドレス</th>
              <td><%= customer.text_field :email %></td>
            </tr>
            
            <tr>
              <th scope="row">会員ステータス</th>
              <td>
                <%= customer.label :is_deleted, '有効' %>
                <%= customer.radio_button :is_deleted, :false %>
                <%= customer.label :is_deleted, '退会' %>
                <%= customer.radio_button :is_deleted, :true %>
              </td>
            </tr>
            
          </tbody>
        </table>
        
          <div class="col-8 offset-2">
            <%= customer.submit '変更を保存', class: 'btn btn-success' %>
          </div>
          
          <% end %>
    </div>
  </main>
  
  

app/views/admin/customers/index.html.erb
<%= render 'admin/nav' %>

<main>
  <div class="container">
    <div class="text-center">
      <div class="col-2 bg-light mt-5 ml-2">
        <h2>会員一覧</h2>
      </div>
          
      <table class="table mt-5">
          <thead>
            <tr>
              <th scope="col" style="width: 10%">会員ID</th>
              <th scope="col" style="width: 20%">氏名</th>
              <th scope="col" style="width: 40%">メールアドレス</th>
              <th scope="col" style="width: 30%">ステータス</th>
            </tr>
          </thead> 
                      
                      
          <tbody>
            <% @customers.each do |customer| %>
            <tr> 
              <td>
                <%= customer.id %>
              </td>  
              <td>
                <%= link_to customer.full_name + "様", admin_customer_path(customer.id) %>
              </td> 
              
              <td>
                <%= customer.email %>
              </td>
              <td>
                <% if customer.is_deleted %>
                  <%= '退会' %>
                <% else %>
                  <p class="text-success">
                  <%= '有効' %>
                </p>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
      </table>
            
      </div>
    </div>
  </main>

app/views/admin/customers/show.html.erb
<%= render 'admin/nav' %>

<main>
  <div class="container">
    <div class="text-center">
      <div class="row">
        <div class="col-5 bg-light mt-5">
          <h2><%= @customer.first_name %><%= @customer.last_name %> 様の会員詳細</h2>
        </div>
      </div>
      
      <div class="row">
        <table class="table table-borderless mt-3">
          <tbody>
            <tr>
              <th scope="row">会員ID</th>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <th scope="row">氏名</th>
              <td>
                <%= @customer.first_name %>
                <%= @customer.last_name %>
              </td>
            </tr>
            <tr>
              <th scope="row">フリガナ</th>
              <td> 
                <%= @customer.first_name_kana %>
                <%= @customer.last_name_kana %>
              </td>
            </tr>
            <tr>
              <th scope="row">郵便番号</th>
              <td><%= @customer.postal_code %></td>
            </tr>
            <tr>
              <th scope="row">住所</th>
              <td><%= @customer.address %></td>
            </tr>
            <tr>
              <th scope="row">電話番号</th>
              <td><%= @customer. telephone_number %></td>
            </tr>
            <tr>
              <th scope="row">メールアドレス</th>
              <td><%= @customer.email %></td>
            </tr>
            <tr>
              <th scope="row">会員ステータス</th>
              <td>
                <% if @customer.is_deleted %>
                  <%= '退会' %>
                <% else %>
                  <p class="text-success">
                  <%= '有効' %>
                  </p>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
                    
                    
      <div class="row">
        <div class="col-12 mt-3">
          <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: 'btn btn-success mr-3' %>
          <%= link_to '注文履歴一覧を見る', admin_orders_path, class: 'btn btn-primary' %>
        </div>
      </div>
      
    </div>
  </div>
</main>