config/routes.rb
Rails.application.routes.draw do
 
 
 devise_for :customers, skip:[:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_for :admin, skip:[:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}



scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/items/search' => 'items#search'
  resources :items, only:[:index, :show]
  resources :genres, only: [:show]
  get '/customers/my_page' => 'customers#show'
  get '/cuntomers/unsubscribe' => 'customers#unsubscribe'
  patch '/customers/withdraw' => 'customers#withdraw'
  resources :customers, only:[:edit, :update]
  resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only:[:new, :create, :index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only:[:index, :update, :destroy, :create]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only:[:new, :create, :index, :show]
end


 namespace :admin do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :genres, only:[:index, :create, :edit, :update, :destroy] 
  resources :items, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  resources :customers, only:[:index, :edit, :update, :show]
  resources :orders, only:[:index, :show, :update]
  resources :order_details, only:[:update]
  end

 
 
  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: { 
    payment_waiting: 0, 
    payment_confirmation: 1, 
    in_production: 2, 
    preparing_delivery: 3, 
    delivered: 4 
  }
  
  validates :payment_method, presence: true
  
 
  
  def count_amount
    total = 0
    order_details.each do |order_detail|
      total += order_detail.amount
    end
    return total
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
   before_action :authenticate_admin!
  
  def index
    @orders = Order.all.page(params[:page])
  end
  
  def show
    @order = Order.find(params[:id])
		@order_details = @order.order_details
		@total = 0
		@shipping_cost = 800
  end
  
  def update
    @order = Order.find(params[:id])  #注文詳細の特定
    @order.update(order_params) #注文ステータスの更新
    @order_details = @order.order_details #注文から紐付く注文した商品の取得

 	 if @order.status == "payment_confirmation" #注文ステータスが「入金確認」なら
	    @order_details.update_all(production_status: "production_pending") #製作ステータスを「製作待ち」に更新
	 end
    redirect_to admin_order_path(@order.id), notice: "注文ステータスを更新しました"
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<%= render 'admin/nav' %>

<main>

  <div class="container">
    <div class="text-center">
      <div class="row">
        <div class="col-2 mt-4 bg-light">
          <h4>注文履歴一覧</h4>
        </div>               
          <table class="table mt-5">
          	<tr class="font-weight-bold bg-light text-dark">
          		<th>購入日時</th>
          		<th>購入者</th>
          		<th>注文個数</th>
          		<th>注文ステータス</th>
          	</tr>
          
          <% @orders.each do |order| %>
          	<tr>
          	  <td><%= link_to order[:created_at].strftime("%Y-%m-%d %H:%M"), admin_order_path(order.id) %></td>
          	  
          		<td><%= order.customer.full_name %></td>
          	
          		<td><%= order.count_amount %></td>
          		
          		<td><%= order.status_i18n %></td>
          	</tr>
          <% end %>
          </table>
           
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-2 offset-5">
      <p><%= paginate @orders %></p>
    </div>
  </div>
  

</main>

app/views/admin/orders/show.html.erb
<%= render 'admin/nav' %>

<main>
  <div class="container">
    <div class="text-center">
      <div class="row">
        <div class="col-3 bg-light mt-5">
          <h2>注文履歴詳細</h2>
        </div>
      </div>
      
      
       <table class="table table-borderless">
        <tbody>
          <tr>
            <th scope="row">購入者</th>
            <td> 
              <%= link_to admin_customer_path(@order.customer_id) do %>
    		      <%= @order.customer.full_name %>
    		      <% end %>
    		    </td>
          </tr>
          
          <tr>
            <th scope="row">注文日</th>
            <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
          </tr>
          
          <tr>
            <th scope="row">配送先</th>
            <td>
              〒 <%= @order.postal_code %>  <%= @order.address %>  <%= @order.name %>
            </td>
          </tr>
          
          <tr>
            <th scope="row">支払方法</th>
            <td> <%= @order.payment_method_i18n %></td>
          </tr>
          
          <tr>
            <th scope="row">注文ステータス</th>
            <td>
              <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true  do |f| %>
                <%= f.select :status, Order.statuses_i18n.invert, class:"form-control form-control-sm col-1" %>
                <%= f.submit "更新", class:"btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
                      
                              
      <div class="row">                      
      
        <div class="col-7">
          <table class="table ">
            <tr class="bg-light">
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
              <th></th>
            </tr>
            
            <% @order_details.each do |order_detail| %>
            
            <tr>
              <td><%= order_detail.item.name %></td>
              <td>¥ <%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
              <td><%= order_detail.amount %></td>
              <td>¥ <%= order_detail.item.with_tax_price * order_detail.amount %></td>
                <% @total += order_detail.item.with_tax_price * order_detail.amount %>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true  do |f| %>
                <!--#showページの６４行目のurl指定が間違っていた。admin_order_pathをadmin_order_detail_path似変更-->
                
      		        <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert,  class:"form-control form-control-sm col-1" %>
                    <%= f.submit "更新", class:"btn btn-success" %>
                <% end %>
              </td>
             <% end %>
    
              
          </table>
        </div>
        
        <div class="col align-self-end">
          <table class="table">
            <tbody>
  
              <tr>
                <td>商品合計</td>
                <td>¥ <%= @total %>円</td>
              </tr>
    
              <tr>
                <td>送料</td>
                <td>¥ <%= @shipping_cost %>円</td>
              </tr>
    
              <tr>
                <td>請求合計金額</td>
                <td>¥ <%= @total + @shipping_cost %>円</td>
              </tr>
              
            </tbody>
          </table>
        </div>
      </div>   
    </div>
  </div>
</main>
 
 